package main

// Plugin holds the display name and Windows zip download URL for one plugin.
// Source: https://www.patreon.com/posts/all-download-34851999
type Plugin struct {
	Name   string
	ZipURL string
}

// Plugins is the complete list of Analog Obsession plugins that ship a Windows zip.
// Sorted ascending alphabetically (A → Z), case-insensitive.
// Bundles (COLOR_BUNDLE, FET BUNDLE, etc.) omitted — Patreon-post-only links.
var Plugins = []Plugin{
	{Name: "AHEAD",      ZipURL: "https://analogobsession.com/wp-content/uploads/2024/07/AHEAD_1.0.zip"},
	{Name: "ATONE",      ZipURL: "https://analogobsession.com/wp-content/uploads/2024/04/ATONE_1.0.zip"},
	{Name: "ATTRACTOR",  ZipURL: "https://analogobsession.com/wp-content/uploads/2025/02/ATTRACTOR_1.0.zip"},
	{Name: "BLENDEQ",    ZipURL: "https://analogobsession.com/wp-content/uploads/2023/05/BLENDEQ_2.0.zip"},
	{Name: "BlackVibe",  ZipURL: "https://analogobsession.com/wp-content/uploads/2022/08/BlackVibe_2.0.zip"},
	{Name: "BritChannel",ZipURL: "https://analogobsession.com/wp-content/uploads/2023/03/BritChannel_7.0.zip"},
	{Name: "Britpressor",ZipURL: "https://analogobsession.com/wp-content/uploads/2023/03/Britpressor_3.0.zip"},
	{Name: "BritPRE",    ZipURL: "https://analogobsession.com/wp-content/uploads/2023/03/BritPre_2.0.zip"},
	{Name: "BUSTERse",   ZipURL: "https://analogobsession.com/wp-content/uploads/2022/12/BUSTERse_7.0.zip"},
	{Name: "BXQ",        ZipURL: "https://analogobsession.com/wp-content/uploads/2023/05/BXQ_5.0.zip"},
	{Name: "CHANNEV",    ZipURL: "https://analogobsession.com/wp-content/uploads/2023/02/CHANNEV_2.0.zip"},
	{Name: "Chopa",      ZipURL: "https://analogobsession.com/wp-content/uploads/2022/06/Chopa_3.0.zip"},
	{Name: "CITE",       ZipURL: "https://analogobsession.com/wp-content/uploads/2024/05/CITE_1.0.zip"},
	{Name: "COMBOX",     ZipURL: "https://analogobsession.com/wp-content/uploads/2023/09/COMBOX_6.0.zip"},
	{Name: "COMPER",     ZipURL: "https://analogobsession.com/wp-content/uploads/2022/11/COMPER_1.1.zip"},
	{Name: "dBComp",     ZipURL: "https://analogobsession.com/wp-content/uploads/2022/12/dBComp_2.0.zip"},
	{Name: "Distox",     ZipURL: "https://analogobsession.com/wp-content/uploads/2024/02/CB_Distox_1.0.zip"},
	{Name: "DrGate",     ZipURL: "https://analogobsession.com/wp-content/uploads/2024/11/DrGate_1.0.zip"},
	{Name: "EDComp",     ZipURL: "https://analogobsession.com/wp-content/uploads/2025/05/EDComp_1.0.zip"},
	{Name: "FetCB",      ZipURL: "https://analogobsession.com/wp-content/uploads/2023/11/FetCB_1.0.zip"},
	{Name: "FETish",     ZipURL: "https://analogobsession.com/wp-content/uploads/2023/04/FETish_6.0.zip"},
	{Name: "FetDrive",   ZipURL: "https://analogobsession.com/wp-content/uploads/2023/04/FetDrive_3.0.zip"},
	{Name: "FetSnap",    ZipURL: "https://analogobsession.com/wp-content/uploads/2023/04/FetSnap_3.0.zip"},
	{Name: "FIVER",      ZipURL: "https://analogobsession.com/wp-content/uploads/2026/01/FIVER_5.0.zip"},
	{Name: "Frank",      ZipURL: "https://analogobsession.com/wp-content/uploads/2023/05/Frank_3.0.zip"},
	{Name: "FrankCS",    ZipURL: "https://analogobsession.com/wp-content/uploads/2023/05/FrankCS_2.0.zip"},
	{Name: "G395a",      ZipURL: "https://analogobsession.com/wp-content/uploads/2023/05/G395a_2.0.zip"},
	{Name: "GrapHack",   ZipURL: "https://analogobsession.com/wp-content/uploads/2023/04/GrapHack_1.1.zip"},
	{Name: "Harqules",   ZipURL: "https://analogobsession.com/wp-content/uploads/2023/05/Harqules_5.0.zip"},
	{Name: "HLQSE",      ZipURL: "https://analogobsession.com/wp-content/uploads/2023/05/HLQSE_5.0.zip"},
	{Name: "INDEQ",      ZipURL: "https://analogobsession.com/wp-content/uploads/2025/08/INDEQ_1.0.zip"},
	{Name: "KABIN",      ZipURL: "https://analogobsession.com/wp-content/uploads/2024/08/KABIN_3.0.zip"},
	{Name: "KOLIN",      ZipURL: "https://analogobsession.com/wp-content/uploads/2023/02/Kolin_5.1.zip"},
	{Name: "KolinMB",    ZipURL: "https://analogobsession.com/wp-content/uploads/2023/06/KolinMB_1.0.zip"},
	{Name: "KONSOL",     ZipURL: "https://analogobsession.com/wp-content/uploads/2021/02/KONSOL_3.0.zip"},
	{Name: "LALA",       ZipURL: "https://analogobsession.com/wp-content/uploads/2023/01/LALA_3.1.zip"},
	{Name: "LAEA",       ZipURL: "https://analogobsession.com/wp-content/uploads/2026/03/LAEA_1.2.zip"},
	{Name: "LOADES",     ZipURL: "https://analogobsession.com/wp-content/uploads/2024/09/LOADES_2.0.zip"},
	{Name: "LOVEND",     ZipURL: "https://analogobsession.com/wp-content/uploads/2021/05/LOVEND_2.0.zip"},
	{Name: "MAXBAX",     ZipURL: "https://analogobsession.com/wp-content/uploads/2023/12/MAXBAX_2.0.zip"},
	{Name: "MERICA",     ZipURL: "https://analogobsession.com/wp-content/uploads/2023/09/MERICA_4.0.zip"},
	{Name: "MidBoss",    ZipURL: "https://analogobsession.com/wp-content/uploads/2025/10/MidBoss_1.0.zip"},
	{Name: "MPReq",      ZipURL: "https://analogobsession.com/wp-content/uploads/2023/12/MPReq_5.0.zip"},
	{Name: "MythPre",    ZipURL: "https://analogobsession.com/wp-content/uploads/2025/04/MythPre_1.0.zip"},
	{Name: "N492ME",     ZipURL: "https://analogobsession.com/wp-content/uploads/2023/12/N492ME_7.0.zip"},
	{Name: "OAQ",        ZipURL: "https://analogobsession.com/wp-content/uploads/2023/12/OAQ_5.0.zip"},
	{Name: "OSS",        ZipURL: "https://analogobsession.com/wp-content/uploads/2022/12/OSS_6.0.zip"},
	{Name: "PEDALz",     ZipURL: "https://analogobsession.com/wp-content/uploads/2024/08/PEDALz_2.0.zip"},
	{Name: "POORTEC",    ZipURL: "https://analogobsession.com/wp-content/uploads/2025/01/POORTEC_1.0.zip"},
	{Name: "PreBOX",     ZipURL: "https://analogobsession.com/wp-content/uploads/2024/02/CB_PreBOX_1.0.zip"},
	{Name: "RazorClip",  ZipURL: "https://analogobsession.com/wp-content/uploads/2026/02/RazorClip_1.0.zip"},
	{Name: "Rare",       ZipURL: "https://analogobsession.com/wp-content/uploads/2023/10/RB_Rare_1.0.zip"},
	{Name: "RareSE",     ZipURL: "https://analogobsession.com/wp-content/uploads/2023/10/RB_RareSE_1.0.zip"},
	{Name: "ReLife",     ZipURL: "https://analogobsession.com/wp-content/uploads/2024/10/ReLife_2.0.zip"},
	{Name: "Room041",    ZipURL: "https://analogobsession.com/wp-content/uploads/2024/09/Room041_2.0.zip"},
	{Name: "SPECOMP",    ZipURL: "https://analogobsession.com/wp-content/uploads/2022/12/SPECOMP_2.0.zip"},
	{Name: "SSQ",        ZipURL: "https://analogobsession.com/wp-content/uploads/2023/12/SSQ_7.0.zip"},
	{Name: "STEQ",       ZipURL: "https://analogobsession.com/wp-content/uploads/2023/12/STEQ_4.0.zip"},
	{Name: "SweetDrums", ZipURL: "https://analogobsession.com/wp-content/uploads/2021/11/SweetDrums_4.0.zip"},
	{Name: "SweetVox",   ZipURL: "https://analogobsession.com/wp-content/uploads/2021/11/SweetVox_4.0.zip"},
	{Name: "TILTA",      ZipURL: "https://analogobsession.com/wp-content/uploads/2023/12/TILTA_2.0.zip"},
	{Name: "TRAX",       ZipURL: "https://analogobsession.com/wp-content/uploads/2024/02/TRAX_2.0.zip"},
	{Name: "TREQ",       ZipURL: "https://analogobsession.com/wp-content/uploads/2023/07/TREQ_6.0.zip"},
	{Name: "TUBA",       ZipURL: "https://analogobsession.com/wp-content/uploads/2023/02/TUBA_3.0.zip"},
	{Name: "TuPRE",      ZipURL: "https://analogobsession.com/wp-content/uploads/2023/02/TuPRE_3.0.zip"},
	{Name: "UREQ",       ZipURL: "https://analogobsession.com/wp-content/uploads/2023/08/UREQ_1.0.zip"},
	{Name: "VariMoon",   ZipURL: "https://analogobsession.com/wp-content/uploads/2022/12/VariMoon_6.0.zip"},
	{Name: "YALA",       ZipURL: "https://analogobsession.com/wp-content/uploads/2022/12/YALA_6.0.zip"},
}
